### PR TITLE
[JENKINS-28932] Added warLibExcludes parameter

### PR DESCRIPTION
**Pull request by oleg-nenashev**
The comma-separated list of library files, which should not be copied to the target HPI file. Supported formats: jar, ejb, ejb-client, tld, par.

Purpose of the change: force the exclusion of JAR files, which are known to be completely shaded and relocated.

https://issues.jenkins-ci.org/browse/JENKINS-28933

@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
Could you investigate how 'war' packaging works in this case?
@aheritier Isn't it continuation of story "unhardcode jar packaging and support shade"?

**Comment by aheritier** [comment]
@KostyaSha Yes I think it is

**Comment by oleg-nenashev** [comment]
I doubt we will be able to change the default behavior due to the risk of missing libs if "plugin B takes the dependency from another plugin declaring the unused dependency".

@KostyaSha @aheritier 
Is it possible to consider the manual contents management as a temporary solution?

**Comment by recena** [comment]
:+1: But I would use `hpiArtifactExcludes` instead of `warLibExcludes`

**Comment by oleg-nenashev** [comment]
> But I would use hpiArtifactExcludes instead of warLibExcludes

All other parameters have the same prefix, so I think it's OK

**Comment by stephenc** [comment]
Favour a list of things to pass to artifact filters than a comma separated string... only use comma separated strings when dealing with command line properties. this is something we expect to live in the pom config

**Comment by oleg-nenashev** [comment]
@KostyaSha 
Investigated maven-war-plugin. They use a similar approach, but a relative path is being used

```
<project>
  ...
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <!--
            Exclude JCL and LOG4J since all logging should go through SLF4J.
            Note that we're excluding log4j-<version>.jar but keeping
            log4j-over-slf4j-<version>.jar
          -->
          <packagingExcludes>
            WEB-INF/lib/commons-logging-*.jar,
            %regex[WEB-INF/lib/log4j-(?!over-slf4j).*.jar]
          </packagingExcludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
  ...
</project>
```

**Comment by stephenc** [comment]
maven artifact filters has some helper methods so you could use a list of strings that get parsed by artifact filters

**Comment by oleg-nenashev** [comment]
Seems a copy-pasting from maven-war-plugin is the best solution

**Comment by recena** [comment]
@oleg-nenashev Then, the best option is `packagingExcludes`;)

**Comment by KostyaSha** [comment]
One more thing that i found https://groups.google.com/forum/#!topic/jenkinsci-dev/8x2nrUwHg60

**Comment by oleg-nenashev** [comment]
Does not make much sense anymore

**Pull request closed without merging**
