### PR TITLE
It's OK not to have classes dir.

### PR DESCRIPTION
**Pull request by kohsuke**
... though rare. Previously, this would have caused 'no such directory' error during execution. With this change, now it creates an empty jar file.

### CODE REVIEW

**Comment by kohsuke** [comment]
@reviewbybees

**Comment by aheritier** [comment]
🐝

**Comment by stephenc** [comment]
:ant: if we don't have a classes directory can you auto-generate index.jelly from the Pom description?

**Comment by jglick** [comment]
Ah, good point. We should at a minimum print a warning if `target/classes/index.jelly` is missing—every plugin should have it.

I presume this is somehow related to https://github.com/jenkinsci/jenkins/pull/2754 but @kohsuke is not giving any context.

**Comment by kohsuke** [comment]
l tried to generate `index.jelly` but packaging is a wrong moment to do it. jar has already been created and tests have already run.

I'll just put `index.jelly` manually instead of trying to be smart.

**Pull request closed without merging**
