### PR TITLE
Pick up parent POM 2.11

### PR DESCRIPTION
**Pull request by andresrc**
Plus a couple of other minor changes.

@reviewbybees (esp. @daniel-beck )

### CODE REVIEW

**Comment by daniel-beck** [comment]
The 2.3 parent had the problem that it still referenced the obsolete maven.jenkins-ci.org host name which resulted in [INFRA-588](https://issues.jenkins-ci.org/browse/INFRA-588).

So :+1: for fixing that for future plugin authors.

**Comment by recena** [comment]
🐝  Is there any JIRA issue for that?

**Comment by andresrc** [comment]
@recena: INFRA-588 :) (sorry, quick and "dirty")

**Comment by Vlatombe** [comment]
🐝

**Pull request merged**
