### PR TITLE
[JENKINS-73419] Migrate HPI plugin from EE 8 to EE 9

### PR DESCRIPTION
**Pull request by basil**
Replace dependencies with EE 9 versions in `pom.xml` and update all relevant imports.

### Testing done

Ran `mvn hpi:run`.

### CODE REVIEW

**Comment by basil** [comment]
In draft until EE 9 is available in a core weekly release, at which point the integration tests can be adapted.

**Comment by jglick** [comment]
If I understand correctly, https://github.com/jenkinsci/jenkins/pull/9672 has been released so this should now be released as well? Current plugin 3.57 fails with a `NoClassDefFoundError` when run on a plugin based on current core. Using 3.58-SNAPSHOT fixes it.

**Comment by alecharp** [comment]
I add to use the incrementals of this pull request to be able to `hpi:run` on LDAP plugin (master branch).

**Comment by jglick** [comment]
⇒ https://github.com/jenkinsci/maven-hpi-plugin/releases/tag/maven-hpi-plugin-3.58

**Comment by daniel-beck** [comment]
Caused https://github.com/jenkinsci/maven-hpi-plugin/issues/667

**Pull request merged**
