### PR TITLE
DEBUG: run mvn verify instead of install for maven dependency debug behavior

### PR DESCRIPTION
**Pull request by dduportal**
Related to https://github.com/jenkins-infra/helpdesk/issues/3599

### CODE REVIEW

**Comment by dduportal** [comment]
I'm closing this draft PR: an issue will be opened to describe the IT problem and discuss resolution

**Comment by basil** [comment]
> an issue will be opened

-1 from me for proceeding with Thursday's migration until either this issue is resolved or a member of the Artifactory bandwidth reduction project commits to being assigned the issue after the migration.

**Comment by dduportal** [comment]
> > an issue will be opened
> 
> -1 from me for proceeding with Thursday's migration until either this issue is resolved or a member of the Artifactory bandwidth reduction project commits to being assigned the issue after the migration.

I commit to opening and driving it to resolution as I've already caught the root cause. I only require help in the form of review as I've never used the maven plugin used in the IT to provide the local repo

**Comment by dduportal** [comment]
@basil does https://github.com/jenkinsci/maven-hpi-plugin/issues/534 looks good for you?

**Pull request closed without merging**
