### PR TITLE
Revert support targetPath property for webResources

### PR DESCRIPTION
**Pull request by timja**
- Revert "add test for packaging webresources (#213)"
- Revert "support targetPath property for webResources (#208)"

Fixes https://github.com/jenkinsci/maven-hpi-plugin/issues/299

The above change switched the resource path to:

```
target/solarized-theme
```

instead of
```
src/main/webapp
```

Which prevented live reload of webapp resources which is critical when doing UI development.
(Restarting the `hpi:run` isn't enough either you had to run a packaging goal too to work around it)

It _may_ be possible to add multiple directories to the resource path but not sure if having both `src` and `target` will work.

I tried adding an integration test for this but what I had passed both before and after this change 😢 
https://github.com/jenkinsci/maven-hpi-plugin/compare/master...timja:fix-live-reload?expand=1

I've manually tested this and it fixes the issue, full steps are in the issue description (https://github.com/jenkinsci/maven-hpi-plugin/issues/299)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Could `stapler.resourcePath` be updated to match?

**Review by jglick — APPROVED** [review]
I can cut a release (not sure offhand who else can), so let me know.

**Comment by timja** [comment]
> I can cut a release (not sure offhand who else can), so let me know.

Core team: https://github.com/jenkins-infra/repository-permissions-updater/blob/06c023e956cdc5088fca38d3cb815273d86c3083/permissions/component-maven-hpi-plugin.yml#L8

**Comment by timja** [comment]
Released https://github.com/jenkinsci/maven-hpi-plugin/releases/tag/maven-hpi-plugin-3.25

**Comment by jglick** [comment]
⇒ https://github.com/jenkinsci/plugin-pom/pull/509

**Pull request merged**
