### PR TITLE
[JENKINS-61937] Safely handle missing dependencies when checking for plugin

### PR DESCRIPTION
**Pull request by daniel-beck**
[JENKINS-61937](https://issues.jenkins-ci.org/browse/JENKINS-61937)

No idea how to test this. Thoughts?

### CODE REVIEW

**Comment by jglick** [comment]
> No idea how to test this.

You mean in an IT? I do not know either. Sufficient to test manually against the reproduction case.

**Comment by daniel-beck** [comment]
> First please try

This works too; the difference is that resolution is attempted and there are warnings logged.

@timja How do these two approaches compare in your IDE?

**Comment by timja** [comment]
No errors in IDE with either approach:

image

**Comment by timja** [comment]
@daniel-beck this waiting on anything?

**Comment by daniel-beck** [comment]
I don't know. A maintainer to merge and release and integrate into the parent POM?

**Pull request merged**
