### PR TITLE
Require Apache Maven 3.9.6 or later

### LINKED ISSUE #667: HPI Plugin 3.58 fails core build on Maven ≤ 3.9.5
### Jenkins and plugins versions report

n/a

### What Operating System are you using (both controller, and any agents involved in the problem)?

n/a

### Reproduction steps

1. Put Maven 3.9.5 on the PATH
2. Check out jenkinsci/jenkins
3. mvn clean install -Pquick-build

### Expected Results

It works

### Actual Results

```
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.58-SNAPSHOT:record-core-location (default) on project jenkins-core: Execution default of goal org.jenkins-ci.tools:maven-hpi-plugin:3.58-SNAPSHOT:record-core-location failed: Unable to load the mojo 'record-core-location' (or one of its required components) from the plugin 'org.jenkins-ci.tools:maven-hpi-plugin:3.58-SNAPSHOT': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for PluginWorkspaceMap was bound.
[ERROR]   while locating RecordCoreLocationMojo
[ERROR]   at ClassRealm[plugin>org.jenkins-ci.tools:maven-hpi-plugin:3.58-SNAPSHOT, parent: ClassLoaders$AppClassLoader@42110406]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating Mojo annotated with @Named("org.jenkins-ci.tools:maven-hpi-plugin:3.58-SNAPSHOT:record-core-location")
[ERROR] 
[ERROR] 1 error
[ERROR] 
[ERROR] ======================
[ERROR] Full classname legend:
[ERROR] ======================
[ERROR] ClassLoaders$AppClassLoader: "jdk.internal.loader.ClassLoaders$AppClassLoader"
[ERROR] Mojo:                        "org.apache.maven.plugin.Mojo"
[ERROR] Named:                       "com.google.inject.name.Named"
[ERROR] PlexusBindingModule:         "org.eclipse.sisu.plexus.PlexusBindingModule"
[ERROR] PluginWorkspaceMap:          "org.jenkinsci.maven.plugins.hpi.PluginWorkspaceMap"
[ERROR] RecordCoreLocationMojo:      "org.jenkinsci.maven.plugins.hpi.RecordCoreLocationMojo"
[ERROR] WireModule:                  "org.eclipse.sisu.wire.WireModule"
[ERROR] ========================
[ERROR] End of classname legend:
[ERROR] ========================
[ERROR] 
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: org.jenkins-ci.tools:maven-hpi-plugin:3.58-SNAPSHOT:record-core-location
[ERROR] -> [Help 1]
```

### Anything else?

Bisected to https://github.com/jenkinsci/maven-hpi-plugin/pull/652

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by Vlatombe**
Previous changes in Maven require 3.9.6 or later for Java 17 compatibility.  Fixes #667

See also
* https://github.com/jenkinsci/pom/pull/612
* https://github.com/jenkinsci/plugin-pom/pull/1018

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Thanks!  We've been running Apache Maven 3.9.9 and its predecessor versions on ci.jenkins.io and its friends (like release.ci.jenkins.io) since those versions were released.  No issues detected as far as I recall.

**Review by jglick — APPROVED** [review]

**Review by basil — APPROVED** [review]
Thanks for the PR! There are a few other places in the ecosystem where we have a 3.8.1 baseline, such as `acceptance-test-harness` and other Jenkins Maven plugins (e.g., `access-modifier-checker`). I will try to hunt those down and update them as well.

**Comment by basil** [comment]
> I will try to hunt those down and update them as well.

I moved some of the rest of the ecosystem to Maven 3.9.6 as well. I did not have the time to look at `incrementals-tools`.

**Comment by batmat** [comment]
Should this change not be released (would be 3.59 I assume)? 
So we can propagate this requirement around, e.g. on https://github.com/jenkinsci/plugin-pom/blob/5485e031ff8f6de66291f02626cd959aba62320f/pom.xml#L77 and https://github.com/jenkinsci/pom/blob/66f86b9fad7fc5112c21055017d40568ce294e15/pom.xml#L98 ?

**Comment by Vlatombe** [comment]
I don't think it is that urgent, because of https://github.com/jenkinsci/pom/pull/612 & https://github.com/jenkinsci/plugin-pom/pull/1018 doing the same check essentially earlier in the build lifecycle.
Call it defense in depth.

However, this makes me think that we could have found out about this issue earlier, if we had a build of maven-hpi-plugin using the minimum maven version that is specified in the build. Under this assumption, I think the plugin ITs would have failed in such an environment.

**Pull request merged**
