### PR TITLE
[JENKINS-38791] Blueocean js extension plugin create archetype

### PR DESCRIPTION
**Pull request by tfennelly**
[JENKINS-38791](https://issues.jenkins-ci.org/browse/JENKINS-38791)

Changes to allow the hpi plugin to be used to creating a Blue Ocean extension plugin.

Run the same as the existing archetype, accept the name is suffixed with "boext" e.g.

```
mvn -U org.jenkins-ci.tools:maven-hpi-plugin:createboext
```

Of course this is not released yet, so you'd need to build it and run with the version included ...

```
mvn -U org.jenkins-ci.tools:maven-hpi-plugin:1.121-SNAPSHOT:createboext
```

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
OH this is awesome - I will take it for a test drive!

**Comment by michaelneale** [comment]
OK I build the fork locally and installed - than ran the command. Told it blue ocean version of 1.0.0-b07 etc, but when I try to mvn install the generated project: 

```
[INFO] Unpacking /Users/michaelneale/.m2/repository/com/github/eirslett/npm/3.10.3/npm-3.10.3.tar.gz into /Users/michaelneale/projects/scratch/mic/node/node_modules
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ mic ---
[INFO] Running 'npm install' in /Users/michaelneale/projects/scratch/mic
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[INFO] 
[INFO] > mic@0.0.1 postinstall /Users/michaelneale/projects/scratch/mic
[INFO] > node postinstall.js
[INFO] 
[ERROR] module.js:457
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'npm'
[ERROR]     at Function.Module._resolveFilename (module.js:455:15)
[ERROR]     at Function.Module._load (module.js:403:25)
[ERROR]     at Module.require (module.js:483:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at Object.<anonymous> (/Users/michaelneale/projects/scratch/mic/postinstall.js:9:13)
[ERROR]     at Module._compile (module.js:556:32)
[ERROR]     at Object.Module._extensions..js (module.js:565:10)
[ERROR]     at Module.load (module.js:473:32)
[ERROR]     at tryModuleLoad (module.js:432:12)
[ERROR]     at Function.Module._load (module.js:424:3)
```

**Comment by tfennelly** [comment]
@michaelneale ahhh .... I'd have thought npm would be in your global packs. I will try it on another box here and see if I can repro your issue. Thanks for trying.

And yes ... `gulpfile.js` is no longer mandatory, but can be added if you want to do more "advanced" stuff.

**Comment by tfennelly** [comment]
@michaelneale hmmmm ... I just checked this out and ran it on my other machine and it worked just fine.

**Comment by tfennelly** [comment]
Okay ... managed to reproduce this in a docker container ... obviously something to do with how NPM is installed on the system and I can't remember how I did it on my machines and how it ight be different.

Thanks for catching this @michaelneale  !!!

**Comment by tfennelly** [comment]
@michaelneale Should work for you now I hope. Pull new commits.

**Comment by michaelneale** [comment]
Very nice @tfennelly :bee: from me. Works as advertised. 

My one Q is the move away from gulpfile. I had to look at the package.json to know what to do (wwas easy enough, and worked well) but lots of other docs in the past says gulp - is there a reason to move away from it (don't get me wrong, love how this works, just not sure of reasoning why)

**Comment by tfennelly** [comment]
@michaelneale `mvn clean install` is all you need to do to build it. Sure if you want to just run just the node bits it's often the case that you do need to look into the `package.json` for a package to see how it's built, so I don't think that's very new for people that are somewhat familiar with node projects. For everyone else, maybe we need a few pointer docs.

The point of this is to decouple the building of the node components from the maven pom and to only use maven for providing the node/npm environment and the phase triggers to execute build and test at the appropriate times wrt the maven/java components. The specifics of what should get executed in node at these times is no longer in the pom, which is a good thing imo. It's not down to the `package.json` to define what needs to happen, which is more flexible etc.

As for using gulp or a `gulpfile.js` ... we can and do use it (see https://github.com/jenkinsci/blueocean-plugin/pull/558), but it's no longer mandatory.

**Comment by michaelneale** [comment]
Nice :shipit: LGTM

**Comment by i386** [comment]
@tfennelly this work is really good - whatever became of it?

**Comment by tfennelly** [comment]
@i386 It became a Yeoman generator: https://www.npmjs.com/package/generator-blueocean-usain

**Pull request closed without merging**
