### PR TITLE
[JENKINS-54807] Use PlatformClassLoader if available in the JVM

### PR DESCRIPTION
**Pull request by alecharp**
[JENKINS-54807](https://issues.jenkins-ci.org/browse/JENKINS-54807)

With this, it is possible to use the PlatformClassLoader if we are running the plugin
from a Java 9+ JVM.

### CODE REVIEW

**Comment by alecharp** [comment]
BTW, I tested this on `versioncolumn` plugin, and as long as we make sure to use a Java 11 ready Jenkins core, it's working perfectly.

**Comment by oleg-nenashev** [comment]
```
[WARNING] Could not validate integrity of download from https://repo.jenkins-ci.org/public/org/kohsuke/stapler/stapler-parent/1.256-SNAPSHOT/stapler-parent-1.256-20181020.094233-5.pom.sha1: Checksum validation failed, no checksums available

[INFO] ..FAILED (1872.2 s)

```

I suspect @jglick has created an integration test for Incrementals at some point, and the incrementals release in the integration test is gone

**Comment by jglick** [comment]
> I suspect @jglick has created an integration test for Incrementals at some point

No, I do not think so.

> the incrementals release in the integration test

`1.256-20181020.094233-5` is a timestamped snapshot, not a release.

**Comment by oleg-nenashev** [comment]
I do not remember. But 🤷‍♂️ , the build passed. Maybe it was just an infra flakiness

**Comment by alecharp** [comment]
From the build log, it was the `compile-fork-it` test (
https://github.com/jenkinsci/maven-hpi-plugin/tree/master/src/it/compile-fork-it)
which was failing.

Le jeu. 31 janv. 2019 à 00:36, Oleg Nenashev <notifications@github.com> a
écrit :

**Comment by oleg-nenashev** [comment]
Anyway, the patch was relesead in 3.3. Thanks a lot Adrien!

**Comment by jglick** [comment]
From the [log](https://ci.jenkins.io/job/Tools/job/maven-hpi-plugin/job/PR-92/1/artifact/target/its/compile-fork-it/build.log):

    org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact avalon-framework:avalon-framework:jar:4.1.3 from/to mrm-maven-plugin (http://localhost:44911): Read timed out

which may have been a transient network outage to Artifactory. (This repository is not yet using the Azure mirror.)

**Pull request merged**
